# DATASET SACADO DE KAGGLE (https://www.kaggle.com/datasets/eoinamoore/historical-nba-data-and-player-box-scores)

In [ ]:
import polars as pl
import pyarrow as pa
import hvplot.polars
import os
os.getcwd()

'/home/mateorzan/polarsNBA/notebooks'

### Cargamos el Dataset como LazyFrame

In [8]:
# Install dependencies as needed:
# pip install kagglehub[polars-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "Games.csv"

# Load the latest version
lf = kagglehub.load_dataset(
  KaggleDatasetAdapter.POLARS,
  "eoinamoore/historical-nba-data-and-player-box-scores",
  file_path,
)

print("First 5 records:", lf.collect().head())

/tmp/ipykernel_645189/3918064176.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  lf = kagglehub.load_dataset(

First 5 records: shape: (5, 22)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gameId   ┆ gameDateT ┆ hometeamC ┆ hometeamN ┆ … ┆ arenaName ┆ arenaCity ┆ arenaStat ┆ officials │
│ ---      ┆ imeEst    ┆ ity       ┆ ame       ┆   ┆ ---       ┆ ---       ┆ e         ┆ ---       │
│ i64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ str       │
│          ┆ str       ┆ str       ┆ str       ┆   ┆           ┆           ┆ str       ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 22500867 ┆ 2026-02-2 ┆ Utah      ┆ Jazz      ┆ … ┆ Delta     ┆ Salt Lake ┆ UT        ┆ Sean      │
│          ┆ 8         ┆           ┆           ┆   ┆ Center    ┆ City      ┆           ┆ Wright,   │
│          ┆ 21:30:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ Brian     │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Forte,    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Sha'…     │
│ 22500866 ┆ 2026-02-2 ┆ Golden    ┆ Warriors  ┆ … ┆ Chase     ┆ San       ┆ CA        ┆ Karl      │
│          ┆ 8         ┆ State     ┆           ┆   ┆ Center    ┆ Francisco ┆           ┆ Lane,     │
│          ┆ 20:30:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ Gediminas │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Petraitis │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …         │
│ 22500865 ┆ 2026-02-2 ┆ Washingto ┆ Wizards   ┆ … ┆ Capital   ┆ Washingto ┆ DC        ┆ Leon      │
│          ┆ 8         ┆ n         ┆           ┆   ┆ One Arena ┆ n         ┆           ┆ Wood,     │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ John      │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Goble,    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Tre Mad…  │
│ 22500864 ┆ 2026-02-2 ┆ Miami     ┆ Heat      ┆ … ┆ Kaseya    ┆ Miami     ┆ FL        ┆ Derrick   │
│          ┆ 8         ┆           ┆           ┆   ┆ Center    ┆           ┆           ┆ Collins,  │
│          ┆ 15:30:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ Mark      │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Lindsay,… │
│ 22500863 ┆ 2026-02-2 ┆ Charlotte ┆ Hornets   ┆ … ┆ Spectrum  ┆ Charlotte ┆ NC        ┆ Sean      │
│          ┆ 8         ┆           ┆           ┆   ┆ Center    ┆           ┆           ┆ Corbin,   │
│          ┆ 13:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ Kevin     │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Scott,    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Suya…     │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

### Analisis de Datos

In [10]:
lf.fetch(5)

/tmp/ipykernel_645189/2725854220.py:1: DeprecationWarning: `LazyFrame.fetch` is deprecated; use `LazyFrame.collect` instead, in conjunction with a call to `head`.
  lf.fetch(5)

shape: (72_853, 22)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ gameId   ┆ gameDateT ┆ hometeamC ┆ hometeamN ┆ … ┆ arenaName ┆ arenaCity ┆ arenaStat ┆ officials │
│ ---      ┆ imeEst    ┆ ity       ┆ ame       ┆   ┆ ---       ┆ ---       ┆ e         ┆ ---       │
│ i64      ┆ ---       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ str       │
│          ┆ str       ┆ str       ┆ str       ┆   ┆           ┆           ┆ str       ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 22500867 ┆ 2026-02-2 ┆ Utah      ┆ Jazz      ┆ … ┆ Delta     ┆ Salt Lake ┆ UT        ┆ Sean      │
│          ┆ 8         ┆           ┆           ┆   ┆ Center    ┆ City      ┆           ┆ Wright,   │
│          ┆ 21:30:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ Brian     │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Forte,    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Sha'…     │
│ 22500866 ┆ 2026-02-2 ┆ Golden    ┆ Warriors  ┆ … ┆ Chase     ┆ San       ┆ CA        ┆ Karl      │
│          ┆ 8         ┆ State     ┆           ┆   ┆ Center    ┆ Francisco ┆           ┆ Lane,     │
│          ┆ 20:30:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ Gediminas │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Petraitis │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …         │
│ 22500865 ┆ 2026-02-2 ┆ Washingto ┆ Wizards   ┆ … ┆ Capital   ┆ Washingto ┆ DC        ┆ Leon      │
│          ┆ 8         ┆ n         ┆           ┆   ┆ One Arena ┆ n         ┆           ┆ Wood,     │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ John      │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Goble,    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Tre Mad…  │
│ 22500864 ┆ 2026-02-2 ┆ Miami     ┆ Heat      ┆ … ┆ Kaseya    ┆ Miami     ┆ FL        ┆ Derrick   │
│          ┆ 8         ┆           ┆           ┆   ┆ Center    ┆           ┆           ┆ Collins,  │
│          ┆ 15:30:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ Mark      │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Lindsay,… │
│ 22500863 ┆ 2026-02-2 ┆ Charlotte ┆ Hornets   ┆ … ┆ Spectrum  ┆ Charlotte ┆ NC        ┆ Sean      │
│          ┆ 8         ┆           ┆           ┆   ┆ Center    ┆           ┆           ┆ Corbin,   │
│          ┆ 13:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆ Kevin     │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Scott,    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Suya…     │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 24600083 ┆ 1946-12-0 ┆ New York  ┆ Knicks    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆ 8         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 24600078 ┆ 1946-12-0 ┆ Boston    ┆ Celtics   ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 24600076 ┆ 1946-12-0 ┆ Philadelp ┆ Warriors  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆ 5         ┆ hia       ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 24600063 ┆ 1946-11-3 ┆ New York  ┆ Knicks    ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆ 0         ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 24600052 ┆ 1946-11-2 ┆ Philadelp ┆ Warriors  ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│          ┆ 6         ┆ hia       ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ 19:00:00  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
lf.schema

/tmp/ipykernel_645189/2177650233.py:1: PerformanceWarning: Resolving the schema of a LazyFrame is a potentially expensive operation. Use `LazyFrame.collect_schema()` to get the schema without this warning.
  lf.schema

Schema([('gameId', Int64),
        ('gameDateTimeEst', String),
        ('hometeamCity', String),
        ('hometeamName', String),
        ('hometeamId', Int64),
        ('awayteamCity', String),
        ('awayteamName', String),
        ('awayteamId', Int64),
        ('homeScore', Int64),
        ('awayScore', Int64),
        ('winner', Int64),
        ('gameType', String),
        ('gameSubtype', String),
        ('gameLabel', String),
        ('gameSubLabel', String),
        ('seriesGameNumber', String),
        ('attendance', Int64),
        ('arenaId', Int64),
        ('arenaName', String),
        ('arenaCity', String),
        ('arenaState', String),
        ('officials', String)])

In [12]:
lf.describe()

shape: (9, 23)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ statistic ┆ gameId    ┆ gameDateT ┆ hometeamC ┆ … ┆ arenaName ┆ arenaCity ┆ arenaStat ┆ official │
│ ---       ┆ ---       ┆ imeEst    ┆ ity       ┆   ┆ ---       ┆ ---       ┆ e         ┆ s        │
│ str       ┆ f64       ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ ---      │
│           ┆           ┆ str       ┆ str       ┆   ┆           ┆           ┆ str       ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ count     ┆ 72853.0   ┆ 72853     ┆ 72853     ┆ … ┆ 974       ┆ 974       ┆ 965       ┆ 974      │
│ null_coun ┆ 0.0       ┆ 0         ┆ 0         ┆ … ┆ 71879     ┆ 71879     ┆ 71888     ┆ 71879    │
│ t         ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ mean      ┆ 2.5779e7  ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ std       ┆ 6.4033e6  ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ min       ┆ 1.0300001 ┆ 1946-11-2 ┆           ┆ … ┆ Acrisure  ┆ Abu Dhabi ┆ AL        ┆ Aaron    │
│           ┆ e7        ┆ 6         ┆           ┆   ┆ Arena     ┆           ┆           ┆ Smith,   │
│           ┆           ┆ 19:00:00  ┆           ┆   ┆           ┆           ┆           ┆ Jacyn    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Goble,   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Jenn…    │
│ 25%       ┆ 2.1300756 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ e7        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 50%       ┆ 2.6200105 ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ e7        ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ 75%       ┆ 2.870036e ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ 7         ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ max       ┆ 6.2500001 ┆ 2026-02-2 ┆ Washingto ┆ … ┆ Xfinity   ┆ Washingto ┆ WI        ┆ Zach     │
│           ┆ e7        ┆ 8         ┆ n         ┆   ┆ Mobile    ┆ n         ┆           ┆ Zarba,   │
│           ┆           ┆ 21:30:00  ┆           ┆   ┆ Arena     ┆           ┆           ┆ Tyler    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Ricks,   │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Brand…   │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [67]:
lf.null_count().collect()

shape: (1, 22)
┌────────┬─────────────────┬──────────────┬──────────────┬────────────┬──────────────┬──────────────┬────────────┬───────────┬───────────┬────────┬──────────┬─────────────┬───────────┬──────────────┬──────────────────┬────────────┬─────────┬───────────┬───────────┬────────────┬───────────┐
│ gameId ┆ gameDateTimeEst ┆ hometeamCity ┆ hometeamName ┆ hometeamId ┆ awayteamCity ┆ awayteamName ┆ awayteamId ┆ homeScore ┆ awayScore ┆ winner ┆ gameType ┆ gameSubtype ┆ gameLabel ┆ gameSubLabel ┆ seriesGameNumber ┆ attendance ┆ arenaId ┆ arenaName ┆ arenaCity ┆ arenaState ┆ officials │
│ ---    ┆ ---             ┆ ---          ┆ ---          ┆ ---        ┆ ---          ┆ ---          ┆ ---        ┆ ---       ┆ ---       ┆ ---    ┆ ---      ┆ ---         ┆ ---       ┆ ---          ┆ ---              ┆ ---        ┆ ---     ┆ ---       ┆ ---       ┆ ---        ┆ ---       │
│ u32    ┆ u32             ┆ u32          ┆ u32          ┆ u32        ┆ u32          ┆ u32          ┆ u32        ┆ u32       ┆ u32       ┆ u32    ┆ u32      ┆ u32         ┆ u32       ┆ u32          ┆ u32              ┆ u32        ┆ u32     ┆ u32       ┆ u32       ┆ u32        ┆ u32       │
╞════════╪═════════════════╪══════════════╪══════════════╪════════════╪══════════════╪══════════════╪════════════╪═══════════╪═══════════╪════════╪══════════╪═════════════╪═══════════╪══════════════╪══════════════════╪════════════╪═════════╪═══════════╪═══════════╪════════════╪═══════════╡
│ 0      ┆ 0               ┆ 0            ┆ 0            ┆ 0          ┆ 0            ┆ 0            ┆ 0          ┆ 0         ┆ 0         ┆ 0      ┆ 0        ┆ 72616       ┆ 68745     ┆ 72459        ┆ 66952            ┆ 71885      ┆ 0       ┆ 71879     ┆ 71879     ┆ 71888      ┆ 71879     │
└────────┴─────────────────┴──────────────┴──────────────┴────────────┴──────────────┴──────────────┴────────────┴───────────┴───────────┴────────┴──────────┴─────────────┴───────────┴──────────────┴──────────────────┴────────────┴─────────┴───────────┴───────────┴────────────┴───────────┘

In [62]:
# Configurar visualización amplia
pl.Config.set_tbl_cols(-1)
pl.Config.set_tbl_width_chars(300)
pl.Config.set_fmt_str_lengths(150)


# Filtrar filas con al menos un nulo
filas_con_nulos = lf.filter(
    pl.any_horizontal(pl.all().is_null())
)

# Ejecutar y ver resultado (primeras 10 filas, por ejemplo)
print(filas_con_nulos.collect())

shape: (72_693, 22)
┌──────────┬──────────────┬──────────────┬──────────────┬────────────┬──────────────┬──────────────┬────────────┬───────────┬───────────┬────────────┬──────────┬─────────────┬──────────────┬──────────────┬──────────────┬────────────┬─────────┬──────────────┬─────────────┬────────────┬──────────────┐
│ gameId   ┆ gameDateTime ┆ hometeamCity ┆ hometeamName ┆ hometeamId ┆ awayteamCity ┆ awayteamName ┆ awayteamId ┆ homeScore ┆ awayScore ┆ winner     ┆ gameType ┆ gameSubtype ┆ gameLabel    ┆ gameSubLabel ┆ seriesGameNu ┆ attendance ┆ arenaId ┆ arenaName    ┆ arenaCity   ┆ arenaState ┆ officials    │
│ ---      ┆ Est          ┆ ---          ┆ ---          ┆ ---        ┆ ---          ┆ ---          ┆ ---        ┆ ---       ┆ ---       ┆ ---        ┆ ---      ┆ ---         ┆ ---          ┆ ---          ┆ mber         ┆ ---        ┆ ---     ┆ ---          ┆ ---         ┆ ---        ┆ ---          │
│ i64      ┆ ---          ┆ str          ┆ str          ┆ i64        ┆ str          ┆ str          ┆ i64        ┆ i64       ┆ i64       ┆ i64        ┆ str      ┆ str         ┆ str          ┆ str          ┆ ---          ┆ i64        ┆ i64     ┆ str          ┆ str         ┆ str        ┆ str          │
│          ┆ str          ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆ str          ┆            ┆         ┆              ┆             ┆            ┆              │
╞══════════╪══════════════╪══════════════╪══════════════╪════════════╪══════════════╪══════════════╪════════════╪═══════════╪═══════════╪════════════╪══════════╪═════════════╪══════════════╪══════════════╪══════════════╪════════════╪═════════╪══════════════╪═════════════╪════════════╪══════════════╡
│ 32500006 ┆ 2026-02-13   ┆              ┆ Team Melo    ┆ 1610616862 ┆              ┆ Team Vince   ┆ 1610616863 ┆ 24        ┆ 25        ┆ 1610616863 ┆ All-Star ┆             ┆ Rising Stars ┆ Championship ┆              ┆ null       ┆ 1000137 ┆ Intuit Dome  ┆ Inglewood   ┆ CA         ┆ Matt Myers,  │
│          ┆ 22:35:00     ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆ Game     ┆             ┆ Final        ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Nate Green,  │
│          ┆              ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Phenizee     │
│          ┆              ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Ransom       │
│ 32500005 ┆ 2026-02-13   ┆              ┆ Team T-Mac   ┆ 1610616864 ┆              ┆ Team Vince   ┆ 1610616863 ┆ 36        ┆ 41        ┆ 1610616863 ┆ All-Star ┆             ┆ Rising Stars ┆ Game 2       ┆              ┆ null       ┆ 1000137 ┆ Intuit Dome  ┆ Inglewood   ┆ CA         ┆ Matt Myers,  │
│          ┆ 21:55:00     ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆ Game     ┆             ┆ Semifinal    ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Nate Green,  │
│          ┆              ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Phenizee     │
│          ┆              ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Ransom       │
│ 32500004 ┆ 2026-02-13   ┆              ┆ Team Melo    ┆ 1610616862 ┆              ┆ Team Austin  ┆ 1610616865 ┆ 40        ┆ 34        ┆ 1610616862 ┆ All-Star ┆             ┆ Rising Stars ┆ Game 1       ┆              ┆ null       ┆ 1000137 ┆ Intuit Dome  ┆ Inglewood   ┆ CA         ┆ Matt Myers,  │
│          ┆ 21:00:00     ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆ Game     ┆             ┆ Semifinal    ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Nate Green,  │
│          ┆              ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Phenizee     │
│          ┆              ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Ransom       │
│ 22500711 ┆ 2026-02-01   ┆ Denver       ┆ Nuggets      ┆ 1610612743 ┆ Oklahoma     ┆ Thunder      ┆ 1610612760 ┆ 111       ┆ 121       ┆ 1610612760 ┆ Regular  ┆ null        ┆ null         ┆ null         ┆ null         ┆ 19900      ┆ 1000046 ┆ Ball Arena   ┆ Denver      ┆ CO         ┆ Tre Maddox,  │
│          ┆ 21:30:00     ┆              ┆              ┆            ┆ City         ┆              ┆            ┆           ┆           ┆            ┆ Season   ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Mitchell     │
│          ┆              ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Ervin,       │
│          ┆              ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Brandon      │
│          ┆              ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Schwab       │
│ 22500703 ┆ 2026-02-01   ┆ San Antonio  ┆ Spurs        ┆ 1610612759 ┆ Orlando      ┆ Magic        ┆ 1610612753 ┆ 112       ┆ 103       ┆ 1610612759 ┆ Regular  ┆ null        ┆ null         ┆ null         ┆ null         ┆ 18354      ┆ 1000118 ┆ Frost Bank   ┆ San Antonio ┆ TX         ┆ John Goble,  │
│          ┆ 21:00:00     ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆ Season   ┆             ┆              ┆              ┆              ┆            ┆         ┆ Center       ┆             ┆            ┆ Nate Green,  │
│          ┆              ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Dannica      │
│          ┆              ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆          ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆ Baroody      │
│ …        ┆ …            ┆ …            ┆ …            ┆ …          ┆ …            ┆ …            ┆ …          ┆ …         ┆ …         ┆ …          ┆ …        ┆ …           ┆ …            ┆ …            ┆ …            ┆ …          ┆ …       ┆ …            ┆ …           ┆ …          ┆ …            │
│ 24600083 ┆ 1946-12-08   ┆ New York     ┆ Knicks       ┆ 1610612752 ┆ Boston       ┆ Celtics      ┆ 1610612738 ┆ 62        ┆ 44        ┆ 1610612752 ┆ Regular  ┆ null        ┆ null         ┆ null         ┆ null         ┆ null       ┆ 0       ┆ null         ┆ null        ┆ null       ┆ null         │
│          ┆ 19:00:00     ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆ Season   ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆              │
│ 24600078 ┆ 1946-12-07   ┆ Boston       ┆ Celtics      ┆ 1610612738 ┆ New York     ┆ Knicks       ┆ 1610612752 ┆ 65        ┆ 90        ┆ 1610612752 ┆ Regular  ┆ null        ┆ null         ┆ null         ┆ null         ┆ null       ┆ 0       ┆ null         ┆ null        ┆ null       ┆ null         │
│          ┆ 19:00:00     ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆ Season   ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆              │
│ 24600076 ┆ 1946-12-05   ┆ Philadelphia ┆ Warriors     ┆ 1610612744 ┆ New York     ┆ Knicks       ┆ 1610612752 ┆ 62        ┆ 51        ┆ 1610612744 ┆ Regular  ┆ null        ┆ null         ┆ null         ┆ null         ┆ null       ┆ 0       ┆ null         ┆ null        ┆ null       ┆ null         │
│          ┆ 19:00:00     ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆ Season   ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆              │
│ 24600063 ┆ 1946-11-30   ┆ New York     ┆ Knicks       ┆ 1610612752 ┆ Philadelphia ┆ Warriors     ┆ 1610612744 ┆ 64        ┆ 60        ┆ 1610612752 ┆ Regular  ┆ null        ┆ null         ┆ null         ┆ null         ┆ null       ┆ 0       ┆ null         ┆ null        ┆ null       ┆ null         │
│          ┆ 19:00:00     ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆ Season   ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆              │
│ 24600052 ┆ 1946-11-26   ┆ Philadelphia ┆ Warriors     ┆ 1610612744 ┆ Boston       ┆ Celtics      ┆ 1610612738 ┆ 66        ┆ 54        ┆ 1610612744 ┆ Regular  ┆ null        ┆ null         ┆ null         ┆ null         ┆ null       ┆ 0       ┆ null         ┆ null        ┆ null       ┆ null         │
│          ┆ 19:00:00     ┆              ┆              ┆            ┆              ┆              ┆            ┆           ┆           ┆            ┆ Season   ┆             ┆              ┆              ┆              ┆            ┆         ┆              ┆             ┆            ┆              │
└──────────┴──────────────┴──────────────┴──────────────┴────────────┴──────────────┴──────────────┴────────────┴───────────┴───────────┴────────────┴──────────┴─────────────┴──────────────┴──────────────┴──────────────┴────────────┴─────────┴──────────────┴─────────────┴────────────┴──────────────┘

AttributeError: module 'polars' has no attribute 'is_duplicated'

In [ ]:
clean_lf = (
    lf
    .filter(pl.col("HomePoints").is_not_null())
    .with_columns(
        pl.col("Date").str.to_date()
    )
)